// app/admin/blog/new/page.tsx - ENHANCED WITH SEO FEATURES & IMAGE FIELD & JSON-LD AUTO-GENERATION
"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  ArrowLeft,
  Save,
  Eye,
  FileText,
  Check,
  X,
  AlertCircle,
  Target,
} from "lucide-react";

// 🚀 NEW IMPORT: Rich Text Editor
import RichTextEditor from "@/components/RichTextEditor";

const categories = [
  "AI Tools",
  "Resume Tips",
  "Cover Letters",
  "Templates",
  "Career Advice",
  "ATS Optimization",
];

// SEO scoring system
interface SEOScore {
  title: number;
  description: number;
  content: number;
  slug: number;
  overall: number;
}

export default function NewBlogPost() {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);

  // 🛠️ UPDATED: Added 'jsonLd' field to the form state
  const [formData, setFormData] = useState({
    title: "",
    slug: "",
    description: "",
    content: "",
    image: "",
    category: "AI Tools",
    readTime: "5 min read",
    featured: false,
    status: "draft" as "draft" | "published",
    metaTitle: "",
    metaDescription: "",
    focusKeyword: "",
    jsonLd: "", // ⬅️ NEW FIELD
  });

  const [seoScore, setSeoScore] = useState<SEOScore>({
    title: 0,
    description: 0,
    content: 0,
    slug: 0,
    overall: 0,
  });

  // Auto-generate slug and meta fields from title/description
  useEffect(() => {
    if (formData.title) {
      const slug = formData.title
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)+/g, "");

      const metaTitle =
        formData.title.length > 60
          ? formData.title.substring(0, 57) + "..."
          : formData.title;

      setFormData((prev) => ({
        ...prev,
        slug,
        metaTitle: prev.metaTitle || metaTitle,
        metaDescription:
          prev.metaDescription || prev.description?.substring(0, 155) || "",
      }));
    }
  }, [formData.title, formData.description]);

  // Calculate SEO score
  useEffect(() => {
    calculateSEOScore();
  }, [formData]);

  const calculateSEOScore = () => {
    let titleScore = 0;
    let descriptionScore = 0;
    let contentScore = 0;
    let slugScore = 0;

    // Content for scoring needs to be text-only
    const textContent = formData.content.replace(/<[^>]*>/g, "");

    // Title scoring (max 25 points)
    if (formData.title.length >= 50 && formData.title.length <= 60)
      titleScore += 25;
    else if (formData.title.length > 0) titleScore += 15;

    // Description scoring (max 25 points)
    if (
      formData.description.length >= 120 &&
      formData.description.length <= 155
    )
      descriptionScore += 25;
    else if (formData.description.length > 0) descriptionScore += 15;

    // Content scoring (max 25 points)
    // Use textContent for scoring
    if (textContent.length >= 300) contentScore += 25;
    else if (textContent.length > 0) contentScore += 10;

    // Slug scoring (max 25 points)
    if (
      formData.slug &&
      formData.slug.includes(formData.focusKeyword?.toLowerCase())
    )
      slugScore += 25;
    else if (formData.slug) slugScore += 15;

    const overall = titleScore + descriptionScore + contentScore + slugScore;

    setSeoScore({
      title: titleScore,
      description: descriptionScore,
      content: contentScore,
      slug: slugScore,
      overall,
    });
  };

  // 🚀 UPDATED: handleSubmit now auto-generates JSON-LD before API call
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);

    // Auto-generate JSON-LD schema
    const baseUrl = "https://www.resumetailorapp.com";
    const autoGeneratedSchema = {
      "@context": "https://schema.org",
      "@type": "Article",
      headline: formData.title,
      description: formData.metaDescription || formData.description,
      image: formData.image
        ? formData.image.startsWith("http")
          ? formData.image
          : `${baseUrl}${
              formData.image.startsWith("/")
                ? formData.image
                : "/" + formData.image
            }`
        : `${baseUrl}/images/blog/default-blog-image.jpg`,
      author: {
        "@type": "Organization",
        name: "ResumeTailorApp",
      },
      publisher: {
        "@type": "Organization",
        name: "ResumeTailorApp",
        // ✅ REMOVED: Logo field (optional)
      },
      datePublished: new Date().toISOString(),
      dateModified: new Date().toISOString(),
      mainEntityOfPage: {
        "@type": "WebPage",
        "@id": `${baseUrl}/blog/${formData.slug}`,
      },
    };

    const submitData = {
      ...formData,
      jsonLd: JSON.stringify(autoGeneratedSchema),
    };

    try {
      const response = await fetch("/api/admin/blog", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(submitData),
      });

      if (response.ok) {
        router.push("/admin");
      } else {
        console.error("Failed to create post");
      }
    } catch (error) {
      console.error("Error creating post:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const getScoreColor = (score: number) => {
    if (score >= 20) return "text-green-600";
    if (score >= 10) return "text-yellow-600";
    return "text-red-600";
  };

  const getScoreIcon = (score: number) => {
    if (score >= 20) return <Check className="w-4 h-4 text-green-600" />;
    if (score >= 10) return <AlertCircle className="w-4 h-4 text-yellow-600" />;
    return <X className="w-4 h-4 text-red-600" />;
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 py-12 px-4">
      <div className="container mx-auto max-w-6xl">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div>
            <Button
              variant="ghost"
              onClick={() => router.push("/admin")}
              className="flex items-center gap-2 text-gray-600 hover:text-gray-800 mb-4"
            >
              <ArrowLeft className="w-4 h-4" />
              Back to Admin
            </Button>
            <h1 className="text-3xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
              Create SEO-Optimized Blog Post
            </h1>
            <p className="text-gray-600 mt-2">
              Follow the SEO guidelines to create content that ranks well on
              search engines
            </p>
          </div>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
            {/* Main Content - 3/4 width */}
            <div className="lg:col-span-3 space-y-6">
              {/* SEO Score Card */}
              <Card className="border-l-4 border-l-blue-500">
                <CardHeader className="pb-3">
                  <CardTitle className="flex items-center gap-2">
                    <Target className="w-5 h-5 text-blue-600" />
                    SEO Score: {seoScore.overall}/100
                  </CardTitle>
                  <CardDescription>
                    Optimize your content for better search engine rankings
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                    <div className="flex items-center gap-2">
                      {getScoreIcon(seoScore.title)}
                      <span>
                        Title:{" "}
                        <strong className={getScoreColor(seoScore.title)}>
                          {seoScore.title}/25
                        </strong>
                      </span>
                    </div>
                    <div className="flex items-center gap-2">
                      {getScoreIcon(seoScore.description)}
                      <span>
                        Description:{" "}
                        <strong className={getScoreColor(seoScore.description)}>
                          {seoScore.description}/25
                        </strong>
                      </span>
                    </div>
                    <div className="flex items-center gap-2">
                      {getScoreIcon(seoScore.content)}
                      <span>
                        Content:{" "}
                        <strong className={getScoreColor(seoScore.content)}>
                          {seoScore.content}/25
                        </strong>
                      </span>
                    </div>
                    <div className="flex items-center gap-2">
                      {getScoreIcon(seoScore.slug)}
                      <span>
                        Slug:{" "}
                        <strong className={getScoreColor(seoScore.slug)}>
                          {seoScore.slug}/25
                        </strong>
                      </span>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Content Card */}
              <Card>
                <CardHeader>
                  <CardTitle>Post Content</CardTitle>
                  <CardDescription>
                    Write engaging content with proper SEO structure
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-6">
                  {/* Focus Keyword */}
                  <div>
                    <label className="text-sm font-medium text-gray-700 mb-2 block">
                      Focus Keyword *
                      <span className="text-xs text-gray-500 ml-2">
                        (Primary keyword for SEO)
                      </span>
                    </label>
                    <Input
                      value={formData.focusKeyword}
                      onChange={(e) =>
                        setFormData((prev) => ({
                          ...prev,
                          focusKeyword: e.target.value,
                        }))
                      }
                      placeholder="e.g., ai resume builder, cover letter tips"
                      required
                    />
                  </div>

                  {/* Title with SEO Guidance */}
                  <div>
                    <div className="flex justify-between items-center mb-2">
                      <label className="text-sm font-medium text-gray-700">
                        Title *
                      </label>
                      <span
                        className={`text-xs ${
                          formData.title.length > 60 ||
                          formData.title.length < 50
                            ? "text-red-600"
                            : "text-green-600"
                        }`}
                      >
                        {formData.title.length}/60 characters
                        {formData.title.length > 60 && " (Too long)"}
                        {formData.title.length < 50 && " (Too short)"}
                      </span>
                    </div>
                    <Input
                      value={formData.title}
                      onChange={(e) =>
                        setFormData((prev) => ({
                          ...prev,
                          title: e.target.value,
                        }))
                      }
                      placeholder="Write an engaging title (50-60 characters)..."
                      required
                    />
                    <div className="text-xs text-gray-500 mt-1">
                      💡 Include your focus keyword naturally in the title
                    </div>
                  </div>

                  {/* Meta Title */}
                  <div>
                    <div className="flex justify-between items-center mb-2">
                      <label className="text-sm font-medium text-gray-700">
                        Meta Title
                        <span className="text-xs text-gray-500 ml-2">
                          (For search results)
                        </span>
                      </label>
                      <span
                        className={`text-xs ${
                          formData.metaTitle.length > 60
                            ? "text-red-600"
                            : "text-green-600"
                        }`}
                      >
                        {formData.metaTitle.length}/60 characters
                      </span>
                    </div>
                    <Input
                      value={formData.metaTitle}
                      onChange={(e) =>
                        setFormData((prev) => ({
                          ...prev,
                          metaTitle: e.target.value,
                        }))
                      }
                      placeholder="Optimized title for search engines..."
                    />
                  </div>

                  {/* Slug with Focus Keyword Check */}
                  <div>
                    <div className="flex justify-between items-center mb-2">
                      <label className="text-sm font-medium text-gray-700">
                        URL Slug *
                      </label>
                      <span
                        className={`text-xs ${
                          formData.slug &&
                          formData.focusKeyword &&
                          formData.slug.includes(
                            formData.focusKeyword.toLowerCase()
                          )
                            ? "text-green-600"
                            : "text-yellow-600"
                        }`}
                      >
                        {formData.focusKeyword &&
                          (formData.slug.includes(
                            formData.focusKeyword.toLowerCase()
                          )
                            ? "✅ Keyword included"
                            : "⚠️ Add keyword")}
                      </span>
                    </div>
                    <Input
                      value={formData.slug}
                      onChange={(e) =>
                        setFormData((prev) => ({
                          ...prev,
                          slug: e.target.value,
                        }))
                      }
                      placeholder="url-slug-with-keywords"
                      required
                    />
                  </div>

                  {/* Description with SEO Guidance */}
                  <div>
                    <div className="flex justify-between items-center mb-2">
                      <label className="text-sm font-medium text-gray-700">
                        Description *
                      </label>
                      <span
                        className={`text-xs ${
                          formData.description.length > 155 ||
                          formData.description.length < 120
                            ? "text-red-600"
                            : "text-green-600"
                        }`}
                      >
                        {formData.description.length}/155 characters
                      </span>
                    </div>
                    <Textarea
                      value={formData.description}
                      onChange={(e) =>
                        setFormData((prev) => ({
                          ...prev,
                          description: e.target.value,
                        }))
                      }
                      placeholder="Write a compelling description that includes your focus keyword (120-155 characters)..."
                      rows={3}
                      required
                    />
                  </div>

                  {/* Meta Description */}
                  <div>
                    <div className="flex justify-between items-center mb-2">
                      <label className="text-sm font-medium text-gray-700">
                        Meta Description
                        <span className="text-xs text-gray-500 ml-2">
                          (Search result snippet)
                        </span>
                      </label>
                      <span
                        className={`text-xs ${
                          formData.metaDescription.length > 155
                            ? "text-red-600"
                            : "text-green-600"
                        }`}
                      >
                        {formData.metaDescription.length}/155 characters
                      </span>
                    </div>
                    <Textarea
                      value={formData.metaDescription}
                      onChange={(e) =>
                        setFormData((prev) => ({
                          ...prev,
                          metaDescription: e.target.value,
                        }))
                      }
                      placeholder="Optimized description for search results..."
                      rows={2}
                    />
                  </div>

                  {/* JSON-LD Schema - Added for manual override (per first instruction block) */}
                  {/* Although auto-generation is used in handleSubmit, keeping the field for transparency/override capability is good practice */}
                  <div>
                    <label className="text-sm font-medium text-gray-700 mb-2 block">
                      JSON-LD Schema
                      <span className="text-xs text-gray-500 ml-2">
                        (Optional - for rich search results)
                      </span>
                    </label>
                    <Textarea
                      value={formData.jsonLd}
                      onChange={(e) =>
                        setFormData((prev) => ({
                          ...prev,
                          jsonLd: e.target.value,
                        }))
                      }
                      placeholder='{"@context":"https://schema.org","@type":"Article","headline":"Your Title"...}'
                      rows={6}
                    />
                    <div className="text-xs text-gray-500 mt-1">
                      💡 This schema is **auto-generated on save** using your
                      Post Content. Only edit here for custom, advanced schema.
                    </div>

                    {/* Note: The 'Auto-Generate Schema Button' is removed as it's now handled by handleSubmit for a cleaner workflow. */}
                  </div>

                  {/* Featured Image Field */}
                  <div>
                    <label className="text-sm font-medium text-gray-700 mb-2 block">
                      Featured Image
                      <span className="text-xs text-gray-500 ml-2">
                        (Optional - displays as blog header)
                      </span>
                    </label>
                    <Input
                      value={formData.image}
                      onChange={(e) =>
                        setFormData((prev) => ({
                          ...prev,
                          image: e.target.value,
                        }))
                      }
                      placeholder="/images/blog/your-image.jpg"
                    />
                    <div className="text-xs text-gray-500 mt-1">
                      💡 Use images from /public/images/blog/ or external URLs
                    </div>

                    {/* Image Preview */}
                    {formData.image && (
                      <div className="mt-2">
                        <div className="text-xs text-gray-600 mb-1">
                          Preview:
                        </div>
                        <div className="border border-gray-200 rounded-lg p-2 bg-gray-50">
                          {formData.image.startsWith("http") ||
                          formData.image.startsWith("/") ? (
                            <div className="aspect-video bg-gray-100 rounded flex items-center justify-center text-gray-400 text-sm">
                              Image: {formData.image.split("/").pop()}
                            </div>
                          ) : (
                            <div className="text-xs text-yellow-600 p-2 bg-yellow-50 rounded">
                              Please provide a valid image URL starting with
                              http://, https://, or /
                            </div>
                          )}
                        </div>
                      </div>
                    )}
                  </div>

                  {/* Content with SEO Guidance - UPDATED WITH RICH TEXT EDITOR */}
                  <div>
                    <div className="flex justify-between items-center mb-2">
                      <label className="text-sm font-medium text-gray-700">
                        Content *
                        <span className="text-xs text-gray-500 ml-2">
                          (Use the toolbar for formatting)
                        </span>
                      </label>
                      <span
                        className={`text-xs ${
                          // 🔧 UPDATED: HTML tag removal for accurate character count
                          formData.content.replace(/<[^>]*>/g, "").length < 300
                            ? "text-yellow-600"
                            : "text-green-600"
                        }`}
                      >
                        {/* 🔧 UPDATED: Display accurate character count */}
                        {formData.content.replace(/<[^>]*>/g, "").length}{" "}
                        characters
                        {formData.content.replace(/<[^>]*>/g, "").length <
                          300 && " (Aim for 300+)"}
                      </span>
                    </div>

                    {/* 🔧 REPLACED: Textarea with RichTextEditor */}
                    <RichTextEditor
                      value={formData.content}
                      onChange={(content) =>
                        setFormData((prev) => ({
                          ...prev,
                          content: content,
                        }))
                      }
                      height={600}
                      placeholder="<h1>Start with a compelling headline that includes your focus keyword</h1><p>Write an engaging introduction that hooks readers and clearly states what they'll learn from this article. Make sure to naturally include your focus keyword in the first paragraph.</p><h2>Break Your Content into Sections</h2><p>Use headings to organize your content logically. This improves readability and helps with SEO.</p><h3>Use Subsections for Detailed Information</h3><p>Break down complex topics into smaller, digestible sections.</p><ul>
                          <li>Use bullet points for lists and key takeaways</li>
                          <li>They make content easier to scan and read</li>
                          <li>Readers appreciate well-organized information</li></ul><h2>Add Value in Every Section</h2><p>Ensure each section provides unique value and insights. Don't just repeat information - add new perspectives and practical advice.</p>"
                    />

                    {/* 🔧 UPDATED: Enhanced SEO Tips for Rich Text */}
                    <div className="text-xs text-gray-500 mt-3 p-3 bg-blue-50 rounded-lg border border-blue-200">
                      <div className="font-semibold text-blue-800 mb-2">
                        💡 SEO & Formatting Tips:
                      </div>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                        <div>
                          • <strong>Use H1</strong> for main title (only one per
                          page)
                        </div>
                        <div>
                          • <strong>Use H2</strong> for main sections
                        </div>
                        <div>
                          • <strong>Use H3</strong> for subsections
                        </div>
                        <div>
                          • <strong>Include focus keyword</strong> in first
                          paragraph
                        </div>
                        <div>
                          • <strong>Add internal links</strong> to related
                          content
                        </div>
                        <div>
                          • <strong>Use bullet points</strong> for better
                          readability
                        </div>
                        <div>
                          • <strong>Include images</strong> with alt text when
                          relevant
                        </div>
                        <div>
                          • <strong>Aim for 300+ words</strong> of valuable
                          content
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Sidebar - 1/4 width */}
            <div className="space-y-6">
              {/* Publish Card */}
              <Card>
                <CardHeader>
                  <CardTitle>Publish</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex gap-2">
                    <Button
                      type="submit"
                      disabled={isLoading || seoScore.overall < 50}
                      className="flex-1 bg-green-600 hover:bg-green-700 text-white"
                      title={
                        seoScore.overall < 50
                          ? "Improve SEO score before publishing"
                          : ""
                      }
                    >
                      <Save className="w-4 h-4 mr-2" />
                      {formData.status === "draft" ? "Save Draft" : "Publish"}
                    </Button>
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() =>
                        window.open(`/blog/${formData.slug}`, "_blank")
                      }
                      disabled={!formData.slug}
                    >
                      <Eye className="w-4 h-4" />
                    </Button>
                  </div>

                  {seoScore.overall < 50 && (
                    <div className="text-xs text-yellow-600 bg-yellow-50 p-2 rounded">
                      ⚠️ SEO score low. Improve content before publishing for
                      better rankings.
                    </div>
                  )}

                  <div className="space-y-2">
                    <label className="text-sm font-medium text-gray-700">
                      Status
                    </label>
                    <select
                      value={formData.status}
                      onChange={(e) =>
                        setFormData((prev) => ({
                          ...prev,
                          status: e.target.value as "draft" | "published",
                        }))
                      }
                      className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm"
                    >
                      <option value="draft">Draft</option>
                      <option value="published">Published</option>
                    </select>
                  </div>
                </CardContent>
              </Card>

              {/* Post Settings */}
              <Card>
                <CardHeader>
                  <CardTitle>Post Settings</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div>
                    <label className="text-sm font-medium text-gray-700 mb-2 block">
                      Category
                    </label>
                    <select
                      value={formData.category}
                      onChange={(e) =>
                        setFormData((prev) => ({
                          ...prev,
                          category: e.target.value,
                        }))
                      }
                      className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm"
                    >
                      {categories.map((category) => (
                        <option key={category} value={category}>
                          {category}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <label className="text-sm font-medium text-gray-700 mb-2 block">
                      Read Time
                    </label>
                    <Input
                      value={formData.readTime}
                      onChange={(e) =>
                        setFormData((prev) => ({
                          ...prev,
                          readTime: e.target.value,
                        }))
                      }
                      placeholder="5 min read"
                    />
                  </div>

                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="featured"
                      checked={formData.featured}
                      onChange={(e) =>
                        setFormData((prev) => ({
                          ...prev,
                          featured: e.target.checked,
                        }))
                      }
                      className="rounded border-gray-300"
                    />
                    <label htmlFor="featured" className="text-sm text-gray-700">
                      Featured Post
                    </label>
                  </div>
                </CardContent>
              </Card>

              {/* SEO Preview */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Target className="w-4 h-4" />
                    SEO Preview
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  <div className="border-l-4 border-l-blue-400 pl-3">
                    <div className="text-blue-600 text-sm font-medium line-clamp-1">
                      {formData.metaTitle ||
                        formData.title ||
                        "Your title will appear here"}
                    </div>
                    <div className="text-green-700 text-xs mt-1">
                      https://yoursite.com/blog/{formData.slug || "your-slug"}
                    </div>
                    <div className="text-gray-600 text-xs line-clamp-2 mt-1">
                      {formData.metaDescription ||
                        formData.description ||
                        "Your meta description will appear here in search results..."}
                    </div>
                  </div>

                  <div className="text-xs text-gray-500 space-y-1">
                    <div>
                      <strong>URL Structure:</strong>
                    </div>
                    <div>/blog/{formData.slug || "your-slug"}</div>
                    {formData.focusKeyword && (
                      <div className="mt-2">
                        <strong>Focus Keyword:</strong> {formData.focusKeyword}
                      </div>
                    )}
                  </div>
                </CardContent>
              </Card>

              {/* Quick SEO Tips */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-sm">Quick SEO Tips</CardTitle>
                </CardHeader>
                <CardContent className="text-xs text-gray-600 space-y-2">
                  <div>✅ Title: 50-60 characters</div>
                  <div>✅ Description: 120-155 characters</div>
                  <div>✅ Content: 300+ words</div>
                  <div>✅ Include focus keyword in URL</div>
                  <div>✅ Use headings (H2, H3)</div>
                  <div>✅ Add internal links</div>
                  <div>✅ Use Alt Text for images</div>
                </CardContent>
              </Card>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}
